import {AdProps} from '@/types/ad-types';
import {Category} from '@/types/category';
import {CommentProps, PostProps} from '@/types/post-item.type';
import {UserTypes} from '@/types/user.types';
import {NotificationItemProps} from './../types/user.types';

export const mockAds: AdProps[] = [
  {
    id: 'summer-sale',
    author: {
      name: 'Janet',
      username: 'fitnesspro',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Janet',
      id: 'user_001',
    },
    type: 'Sponsored',
    title: 'Discover the Future of AI',
    content: `Don't miss out on our massive summer sale! Enjoy up to 50% off on selected items including electronics, fashion, and home essentials. Hurry, offers valid while stock lasts.`,
    imageUrl:
      'https://images.ctfassets.net/hrltx12pl8hq/4kzWG72Pi925q9Gtc6hBQh/6bdbb560251e188bab5d3ea1ad195d6b/1.jpg',
    plan: 'Professional',
    category: 'home',
    price: 30,
    status: 'pending',
    submittedDate: '2023-06-15T10:30:00Z',
    targetUrl: 'https://example.com/fitness-program',
    callToAction: 'Get Started',
  },

  {
    id: 'summer-sale_kit',
    author: {
      name: 'Janet',
      username: 'fitnesspro',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Janet',
      id: 'user_006',
    },
    type: 'Banner',
    title: 'Discover the Future of AI',
    content: `Don't miss out on our massive summer sale! Enjoy up to 50% off on selected items including electronics, fashion, and home essentials. Hurry, offers valid while stock lasts.`,
    imageUrl:
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
    plan: 'Professional',
    category: 'sports',
    price: 30,
    status: 'pending',
    submittedDate: '2023-06-15T10:30:00Z',
    targetUrl: 'https://example.com/fitness-program',
    callToAction: 'Get Started',
  },
  {
    id: 'new-product',
    author: {
      name: 'Carlos',
      username: 'fitnesspro',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos',
      id: 'user_002',
    },
    title: 'New Product Launch',
    type: 'Banner',
    imageUrl:
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
    plan: 'Enterprise',
    category: 'home',
    price: 100,
    status: 'pending',
    submittedDate: '2023-06-14T14:45:00Z',
    targetUrl: 'https://example.com/fitness-program',
  },
  {
    id: 'holiday-special',
    author: {
      name: 'Lilian',
      username: 'fitnesspro',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lilian',
      id: 'user_003',
    },

    type: 'Sponsored',
    title: ' Leveraging AI to improve customer experience - MTN ',
    content: `Escape the stress and unwind with our exclusive holiday packages! Get discounts on flights, hotels, and guided tours to breathtaking destinations across the globe.`,
    plan: 'Basic',
    category: 'home',
    price: 10,
    status: 'approved',
    submittedDate: '2023-06-10T09:15:00Z',
    approvedDate: '2023-06-11T11:20:00Z',
    callToAction: 'Sign Up',
    targetUrl: 'https://example.com/fitness-program',
  },
  {
    id: 'fitness-program',
    author: {
      name: 'Tunde',
      username: 'fitnesspro',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Tunde',
      id: 'user_004',
    },

    type: 'Banner',
    title: 'firnessing',
    imageUrl:
      'https://media.istockphoto.com/id/1316524516/photo/modern-large-luxury-dark-gray-kitchen-closeup.jpg?s=612x612&w=0&k=20&c=FtLMlE9VzOx5o8Vq0H_5xMZ8dDj5MsG0q5NVWSPlVzU=',
    plan: 'Professional',
    category: 'home',
    price: 30,
    status: 'rejected',
    submittedDate: '2023-06-08T16:30:00Z',
    rejectedDate: '2023-06-09T10:45:00Z',
    rejectionReason:
      'Image quality does not meet our standards. Please upload a higher resolution image.',
    targetUrl: 'https://example.com/fitness-program',
  },
  {
    id: 'webinar-signup',
    author: {
      name: 'Musa',
      username: 'fitnesspro',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Musa',
      id: 'user_005',
    },
    type: 'Sponsored',
    title: ' Leveraging AI to improve customer experience - MTN ',
    content: `Join our free live webinar on "The Role of AI in Modern Education". Learn how artificial intelligence is shaping classrooms of the future, improving outcomes, and redefining learning experiences.`,
    imageUrl:
      'https://media.istockphoto.com/id/1316524516/photo/modern-large-luxury-dark-gray-kitchen-closeup.jpg?s=612x612&w=0&k=20&c=FtLMlE9VzOx5o8Vq0H_5xMZ8dDj5MsG0q5NVWSPlVzU=',
    plan: 'Basic',
    category: 'home',
    price: 10,
    status: 'approved',
    submittedDate: '2023-06-05T11:20:00Z',
    approvedDate: '2023-06-06T14:10:00Z',
    callToAction: 'Learn More',
    targetUrl: 'https://example.com/fitness-program',
  },
];

export const Categories: Category[] = [
  {
    id: '1',
    name: 'Technology',
    description: 'Discuss the latest in technology trends and gadgets',
    ch: 'tech',
  },
  {
    id: '2',
    name: 'Travel',
    description: 'Share your travel experiences and recommendations',
    ch: 'trav',
  },
  {
    id: '3',
    name: 'Food',
    description:
      'Food recipes, restaurant recommendations, and culinary adventures',
    ch: 'food',
  },

  {
    id: '4',
    name: 'Sports',
    description: 'Sports news, events, and discussions',
    ch: 'sport',
  },
  {
    id: '5',
    name: 'Politics',
    description: 'Debates and news on politics and government affairs',
    ch: 'pol',
  },
  {
    id: '6',
    name: 'Education',
    description: 'Topics related to schools, learning, and academia',
    ch: 'edu',
  },
  {
    id: '7',
    name: 'Religion',
    description: 'Discussions on faith, beliefs, and spirituality',
    ch: 'rel',
  },
  {
    id: '8',
    name: 'Romance',
    description: 'Love stories, dating advice, and relationship discussions',
    ch: 'rom',
  },
  {
    id: '9',
    name: 'Jobs',
    description: 'Career advice, job opportunities, and work-life tips',
    ch: 'jobs',
  },
  {
    id: '10',
    name: 'News',
    description: 'Breaking news and current events from around the world',
    ch: 'news',
  },
  {
    id: '11',
    name: 'Entertainment',
    description: 'Movies, TV shows, music, and pop culture',
    ch: 'ent',
  },
  {
    id: '12',
    name: 'Celebrity',
    description: 'Celebrity gossip, news, and public appearances',
    ch: 'celeb',
  },
];

// export const Posts: PostProps[] = [
//   {
//     id: '1',
//     userId: '1',
//     username: 'johndoe',
//     displayName: 'John Doe',
//     avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
//     verified: true,
//     categoryId: '1',
//     title: 'The Future of AI',
//     content:
//       'What are your thoughts on the future of artificial intelligence? Share your predictions!',
//     timestamp: new Date(),
//     likes: 150,
//     reposts: 30,
//     bookmarks: 20,
//     comments: 45,
//     views: 500,
//     likedBy: ['2', '3'],
//     category: 'sports',
//   },
//   {
//     id: '2',
//     userId: '2',
//     username: 'janedoe',
//     displayName: 'Jane Doe',
//     avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
//     verified: false,
//     categoryId: '2',
//     title: 'Exploring Southeast Asia',
//     content:
//       'Just got back from an amazing trip to Southeast Asia. Highly recommend visiting Thailand and Vietnam!',
//     timestamp: new Date(),
//     likes: 200,
//     reposts: 45,
//     bookmarks: 30,
//     category: 'sports',
//   },
//   {
//     id: '3',
//     userId: '1',
//     username: 'johndoe',
//     displayName: 'John Doe',
//     avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
//     verified: true,
//     categoryId: '3',
//     title: 'Best Pizza in Town',
//     content:
//       "Tried the new pizza place downtown and it was incredible! Definitely the best pizza I've had in a long time.",
//     timestamp: new Date(),
//     likes: 120,
//     reposts: 25,
//     bookmarks: 15,
//     category: 'news',
//   },
//   {
//     id: '4',
//     userId: '3',
//     username: 'gamerpro',
//     displayName: 'GamerPro',
//     avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Gamer',
//     verified: true,
//     categoryId: '4',
//     title: 'New Game Release',
//     content:
//       'Hyped for the new game releasing next week! Anyone else excited to play?',
//     timestamp: new Date(),
//     likes: 180,
//     reposts: 40,
//     bookmarks: 25,
//     category: 'gaming',
//   },
//   {
//     id: '5',
//     userId: '2',
//     username: 'janedoe',
//     displayName: 'Jane Doe',
//     avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
//     verified: false,
//     categoryId: '5',
//     title: 'Upcoming Marathon',
//     content:
//       'Training for the upcoming marathon. Any tips for long-distance running?',
//     timestamp: new Date(),
//     likes: 160,
//     reposts: 35,
//     bookmarks: 22,
//     category: 'travel',
//   },
// ];

export const Posts: PostProps[] = [
  {
    id: '1',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '1',
    title: 'The Future of AI #1',
    content:
      'What are your thoughts on the future of artificial intelligence? Share your predictions!',
    category: 'sports',
    timestamp: '2025-05-15T18:08:45.078452',
    likes: 168,
    reposts: 44,
    bookmarks: 19,
    comments: 46,
    views: 308,
    likedBy: ['2', '5'],
    images: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=80',
    ],
  },
  {
    id: '2',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '2',
    title: 'Exploring Southeast Asia #2',
    content:
      'Just got back from an amazing trip to Southeast Asia. Highly recommend visiting Thailand and Vietnam!',
    category: 'sports',
    timestamp: '2025-05-15T18:03:45.078452',
    likes: 110,
    reposts: 38,
    bookmarks: 6,
    comments: 46,
    views: 830,
    likedBy: ['3', '1', '1'],
  },
  {
    id: '3',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '3',
    title: 'Best Pizza in Town #3',
    content:
      "Tried the new pizza place downtown and it was incredible! Definitely the best pizza I've had in a long time.",
    category: 'news',
    timestamp: '2025-05-15T17:58:45.078452',
    likes: 152,
    reposts: 12,
    bookmarks: 30,
    comments: 0,
    views: 638,
    likedBy: ['3', '3'],
  },
  {
    id: '4',
    userId: '3',
    username: 'gamerpro',
    displayName: 'GamerPro',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Gamer',
    verified: true,
    categoryId: '4',
    title: 'New Game Release #4',
    content:
      'Hyped for the new game releasing next week! Anyone else excited to play?',
    category: 'gaming',
    timestamp: '2025-05-15T17:53:45.078452',
    likes: 80,
    reposts: 49,
    bookmarks: 39,
    comments: 18,
    views: 152,
    likedBy: ['2'],
  },
  {
    id: '5',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '5',
    title: 'Upcoming Marathon #5',
    content:
      'Training for the upcoming marathon. Any tips for long-distance running?',
    category: 'travel',
    timestamp: '2025-05-15T17:48:45.078452',
    likes: 295,
    reposts: 31,
    bookmarks: 5,
    comments: 8,
    views: 587,
    likedBy: ['1', '1'],
  },
  {
    id: '6',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '1',
    title: 'The Future of AI #6',
    content:
      'What are your thoughts on the future of artificial intelligence? Share your predictions!',
    category: 'sports',
    timestamp: '2025-05-15T17:43:45.078452',
    likes: 94,
    reposts: 46,
    bookmarks: 14,
    comments: 8,
    views: 980,
    likedBy: ['1', '5'],
  },
  {
    id: '7',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '2',
    title: 'Exploring Southeast Asia #7',
    content:
      'Just got back from an amazing trip to Southeast Asia. Highly recommend visiting Thailand and Vietnam!',
    category: 'sports',
    timestamp: '2025-05-15T17:38:45.078452',
    likes: 88,
    reposts: 31,
    bookmarks: 33,
    comments: 2,
    views: 910,
    likedBy: ['1', '2'],
  },
  {
    id: '8',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '3',
    title: 'Best Pizza in Town #8',
    content:
      "Tried the new pizza place downtown and it was incredible! Definitely the best pizza I've had in a long time.",
    category: 'news',
    timestamp: '2025-05-15T17:33:45.078452',
    likes: 98,
    reposts: 19,
    bookmarks: 22,
    comments: 27,
    views: 203,
    likedBy: ['1', '4', '1'],
  },
  {
    id: '9',
    userId: '3',
    username: 'gamerpro',
    displayName: 'GamerPro',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Gamer',
    verified: true,
    categoryId: '4',
    title: 'New Game Release #9',
    content:
      'Hyped for the new game releasing next week! Anyone else excited to play?',
    category: 'gaming',
    timestamp: '2025-05-15T17:28:45.078452',
    likes: 234,
    reposts: 49,
    bookmarks: 19,
    comments: 6,
    views: 857,
    likedBy: ['5', '3', '3'],
  },
  {
    id: '10',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '5',
    title: 'Upcoming Marathon #10',
    content:
      'Training for the upcoming marathon. Any tips for long-distance running?',
    category: 'travel',
    timestamp: '2025-05-15T17:23:45.078452',
    likes: 172,
    reposts: 50,
    bookmarks: 29,
    comments: 26,
    views: 473,
    likedBy: ['4', '3', '5'],
  },
  {
    id: '11',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '1',
    title: 'The Future of AI #11',
    content:
      'What are your thoughts on the future of artificial intelligence? Share your predictions!',
    category: 'sports',
    timestamp: '2025-05-15T17:18:45.078452',
    likes: 141,
    reposts: 44,
    bookmarks: 25,
    comments: 21,
    views: 653,
    likedBy: ['3', '3', '1'],
  },
  {
    id: '12',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '2',
    title: 'Exploring Southeast Asia #12',
    content:
      'Just got back from an amazing trip to Southeast Asia. Highly recommend visiting Thailand and Vietnam!',
    category: 'sports',
    timestamp: '2025-05-15T17:13:45.078452',
    likes: 214,
    reposts: 47,
    bookmarks: 21,
    comments: 2,
    views: 588,
    likedBy: ['4', '4', '5'],
  },
  {
    id: '13',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '3',
    title: 'Best Pizza in Town #13',
    content:
      "Tried the new pizza place downtown and it was incredible! Definitely the best pizza I've had in a long time.",
    category: 'news',
    timestamp: '2025-05-15T17:08:45.078452',
    likes: 74,
    reposts: 26,
    bookmarks: 17,
    comments: 40,
    views: 268,
    likedBy: ['3', '5', '5'],
  },
  {
    id: '14',
    userId: '3',
    username: 'gamerpro',
    displayName: 'GamerPro',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Gamer',
    verified: true,
    categoryId: '4',
    title: 'New Game Release #14',
    content:
      'Hyped for the new game releasing next week! Anyone else excited to play?',
    category: 'gaming',
    timestamp: '2025-05-15T17:03:45.078452',
    likes: 91,
    reposts: 23,
    bookmarks: 8,
    comments: 27,
    views: 365,
    likedBy: ['2', '4'],
  },
  {
    id: '15',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '5',
    title: 'Upcoming Marathon #15',
    content:
      'Training for the upcoming marathon. Any tips for long-distance running?',
    category: 'travel',
    timestamp: '2025-05-15T16:58:45.078452',
    likes: 197,
    reposts: 48,
    bookmarks: 11,
    comments: 37,
    views: 546,
    likedBy: ['4'],
  },
  {
    id: '16',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '1',
    title: 'The Future of AI #16',
    content:
      'What are your thoughts on the future of artificial intelligence? Share your predictions!',
    category: 'sports',
    timestamp: '2025-05-15T16:53:45.078452',
    likes: 277,
    reposts: 40,
    bookmarks: 36,
    comments: 17,
    views: 455,
    likedBy: ['2', '4', '3'],
  },
  {
    id: '17',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '2',
    title: 'Exploring Southeast Asia #17',
    content:
      'Just got back from an amazing trip to Southeast Asia. Highly recommend visiting Thailand and Vietnam!',
    category: 'sports',
    timestamp: '2025-05-15T16:48:45.078452',
    likes: 69,
    reposts: 29,
    bookmarks: 17,
    comments: 21,
    views: 846,
    likedBy: ['5', '4', '1'],
  },
  {
    id: '18',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '3',
    title: 'Best Pizza in Town #18',
    content:
      "Tried the new pizza place downtown and it was incredible! Definitely the best pizza I've had in a long time.",
    category: 'news',
    timestamp: '2025-05-15T16:43:45.078452',
    likes: 113,
    reposts: 52,
    bookmarks: 21,
    comments: 45,
    views: 236,
    likedBy: ['3', '5', '1'],
  },
  {
    id: '19',
    userId: '3',
    username: 'gamerpro',
    displayName: 'GamerPro',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Gamer',
    verified: true,
    categoryId: '4',
    title: 'New Game Release #19',
    content:
      'Hyped for the new game releasing next week! Anyone else excited to play?',
    category: 'gaming',
    timestamp: '2025-05-15T16:38:45.078452',
    likes: 247,
    reposts: 49,
    bookmarks: 22,
    comments: 46,
    views: 155,
    likedBy: ['4', '4'],
  },
  {
    id: '20',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '5',
    title: 'Upcoming Marathon #20',
    content:
      'Training for the upcoming marathon. Any tips for long-distance running?',
    category: 'travel',
    timestamp: '2025-05-15T16:33:45.078452',
    likes: 222,
    reposts: 17,
    bookmarks: 30,
    comments: 37,
    views: 656,
    likedBy: ['4'],
  },
  {
    id: '21',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '1',
    title: 'The Future of AI #21',
    content:
      'What are your thoughts on the future of artificial intelligence? Share your predictions!',
    category: 'sports',
    timestamp: '2025-05-15T16:28:45.078452',
    likes: 252,
    reposts: 40,
    bookmarks: 21,
    comments: 31,
    views: 256,
    likedBy: ['1'],
  },
  {
    id: '22',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '2',
    title: 'Exploring Southeast Asia #22',
    content:
      'Just got back from an amazing trip to Southeast Asia. Highly recommend visiting Thailand and Vietnam!',
    category: 'sports',
    timestamp: '2025-05-15T16:23:45.078452',
    likes: 85,
    reposts: 23,
    bookmarks: 30,
    comments: 39,
    views: 198,
    likedBy: ['1'],
  },
  {
    id: '23',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '3',
    title: 'Best Pizza in Town #23',
    content:
      "Tried the new pizza place downtown and it was incredible! Definitely the best pizza I've had in a long time.",
    category: 'news',
    timestamp: '2025-05-15T16:18:45.078452',
    likes: 183,
    reposts: 48,
    bookmarks: 29,
    comments: 4,
    views: 529,
    likedBy: ['3'],
  },
  {
    id: '24',
    userId: '3',
    username: 'gamerpro',
    displayName: 'GamerPro',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Gamer',
    verified: true,
    categoryId: '4',
    title: 'New Game Release #24',
    content:
      'Hyped for the new game releasing next week! Anyone else excited to play?',
    category: 'gaming',
    timestamp: '2025-05-15T16:13:45.078452',
    likes: 175,
    reposts: 60,
    bookmarks: 23,
    comments: 4,
    views: 120,
    likedBy: ['2', '5', '4'],
  },
  {
    id: '25',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '5',
    title: 'Upcoming Marathon #25',
    content:
      'Training for the upcoming marathon. Any tips for long-distance running?',
    category: 'travel',
    timestamp: '2025-05-15T16:08:45.078452',
    likes: 127,
    reposts: 31,
    bookmarks: 23,
    comments: 24,
    views: 472,
    likedBy: ['5'],
  },
  {
    id: '26',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '1',
    title: 'The Future of AI #26',
    content:
      'What are your thoughts on the future of artificial intelligence? Share your predictions!',
    category: 'sports',
    timestamp: '2025-05-15T16:03:45.078452',
    likes: 119,
    reposts: 34,
    bookmarks: 12,
    comments: 18,
    views: 670,
    likedBy: ['3', '1', '3'],
  },
  {
    id: '27',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '2',
    title: 'Exploring Southeast Asia #27',
    content:
      'Just got back from an amazing trip to Southeast Asia. Highly recommend visiting Thailand and Vietnam!',
    category: 'sports',
    timestamp: '2025-05-15T15:58:45.078452',
    likes: 249,
    reposts: 51,
    bookmarks: 8,
    comments: 3,
    views: 368,
    likedBy: ['4', '2', '5'],
  },
  {
    id: '28',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '3',
    title: 'Best Pizza in Town #28',
    content:
      "Tried the new pizza place downtown and it was incredible! Definitely the best pizza I've had in a long time.",
    category: 'news',
    timestamp: '2025-05-15T15:53:45.078452',
    likes: 165,
    reposts: 59,
    bookmarks: 12,
    comments: 12,
    views: 713,
    likedBy: ['5', '5', '5'],
  },
  {
    id: '29',
    userId: '3',
    username: 'gamerpro',
    displayName: 'GamerPro',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Gamer',
    verified: true,
    categoryId: '4',
    title: 'New Game Release #29',
    content:
      'Hyped for the new game releasing next week! Anyone else excited to play?',
    category: 'gaming',
    timestamp: '2025-05-15T15:48:45.078452',
    likes: 50,
    reposts: 30,
    bookmarks: 8,
    comments: 4,
    views: 101,
    likedBy: ['4', '3', '2'],
  },
  {
    id: '30',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '5',
    title: 'Upcoming Marathon #30',
    content:
      'Training for the upcoming marathon. Any tips for long-distance running?',
    category: 'travel',
    timestamp: '2025-05-15T15:43:45.078452',
    likes: 159,
    reposts: 31,
    bookmarks: 16,
    comments: 34,
    views: 626,
    likedBy: ['2', '1', '5'],
  },
  {
    id: '31',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '1',
    title: 'The Future of AI #31',
    content:
      'What are your thoughts on the future of artificial intelligence? Share your predictions!',
    category: 'sports',
    timestamp: '2025-05-15T15:38:45.078452',
    likes: 148,
    reposts: 60,
    bookmarks: 25,
    comments: 34,
    views: 703,
    likedBy: ['2'],
  },
  {
    id: '32',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '2',
    title: 'Exploring Southeast Asia #32',
    content:
      'Just got back from an amazing trip to Southeast Asia. Highly recommend visiting Thailand and Vietnam!',
    category: 'sports',
    timestamp: '2025-05-15T15:33:45.078452',
    likes: 132,
    reposts: 23,
    bookmarks: 26,
    comments: 36,
    views: 603,
    likedBy: ['3'],
  },
  {
    id: '33',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '3',
    title: 'Best Pizza in Town #33',
    content:
      "Tried the new pizza place downtown and it was incredible! Definitely the best pizza I've had in a long time.",
    category: 'news',
    timestamp: '2025-05-15T15:28:45.078452',
    likes: 173,
    reposts: 19,
    bookmarks: 39,
    comments: 9,
    views: 352,
    likedBy: ['5'],
  },
  {
    id: '34',
    userId: '3',
    username: 'gamerpro',
    displayName: 'GamerPro',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Gamer',
    verified: true,
    categoryId: '4',
    title: 'New Game Release #34',
    content:
      'Hyped for the new game releasing next week! Anyone else excited to play?',
    category: 'gaming',
    timestamp: '2025-05-15T15:23:45.078452',
    likes: 142,
    reposts: 19,
    bookmarks: 14,
    comments: 25,
    views: 937,
    likedBy: ['3', '3'],
  },
  {
    id: '35',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '5',
    title: 'Upcoming Marathon #35',
    content:
      'Training for the upcoming marathon. Any tips for long-distance running?',
    category: 'travel',
    timestamp: '2025-05-15T15:18:45.078452',
    likes: 73,
    reposts: 13,
    bookmarks: 39,
    comments: 10,
    views: 956,
    likedBy: ['1', '3'],
  },
  {
    id: '36',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '1',
    title: 'The Future of AI #36',
    content:
      'What are your thoughts on the future of artificial intelligence? Share your predictions!',
    category: 'sports',
    timestamp: '2025-05-15T15:13:45.078452',
    likes: 89,
    reposts: 47,
    bookmarks: 28,
    comments: 15,
    views: 630,
    likedBy: ['2', '4', '4'],
  },
  {
    id: '37',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '2',
    title: 'Exploring Southeast Asia #37',
    content:
      'Just got back from an amazing trip to Southeast Asia. Highly recommend visiting Thailand and Vietnam!',
    category: 'sports',
    timestamp: '2025-05-15T15:08:45.078452',
    likes: 151,
    reposts: 37,
    bookmarks: 21,
    comments: 45,
    views: 602,
    likedBy: ['1'],
  },
  {
    id: '38',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '3',
    title: 'Best Pizza in Town #38',
    content:
      "Tried the new pizza place downtown and it was incredible! Definitely the best pizza I've had in a long time.",
    category: 'news',
    timestamp: '2025-05-15T15:03:45.078452',
    likes: 167,
    reposts: 42,
    bookmarks: 23,
    comments: 36,
    views: 661,
    likedBy: ['4', '4'],
  },
  {
    id: '39',
    userId: '3',
    username: 'gamerpro',
    displayName: 'GamerPro',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Gamer',
    verified: true,
    categoryId: '4',
    title: 'New Game Release #39',
    content:
      'Hyped for the new game releasing next week! Anyone else excited to play?',
    category: 'gaming',
    timestamp: '2025-05-15T14:58:45.078452',
    likes: 62,
    reposts: 27,
    bookmarks: 5,
    comments: 36,
    views: 984,
    likedBy: ['4', '2'],
  },
  {
    id: '40',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '5',
    title: 'Upcoming Marathon #40',
    content:
      'Training for the upcoming marathon. Any tips for long-distance running?',
    category: 'travel',
    timestamp: '2025-05-15T14:53:45.078452',
    likes: 261,
    reposts: 26,
    bookmarks: 18,
    comments: 42,
    views: 303,
    likedBy: ['5', '1'],
  },
  {
    id: '41',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '1',
    title: 'The Future of AI #41',
    content:
      'What are your thoughts on the future of artificial intelligence? Share your predictions!',
    category: 'sports',
    timestamp: '2025-05-15T14:48:45.078452',
    likes: 248,
    reposts: 28,
    bookmarks: 34,
    comments: 15,
    views: 810,
    likedBy: ['1'],
  },
  {
    id: '42',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '2',
    title: 'Exploring Southeast Asia #42',
    content:
      'Just got back from an amazing trip to Southeast Asia. Highly recommend visiting Thailand and Vietnam!',
    category: 'sports',
    timestamp: '2025-05-15T14:43:45.078452',
    likes: 256,
    reposts: 10,
    bookmarks: 37,
    comments: 25,
    views: 482,
    likedBy: ['4'],
  },
  {
    id: '43',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '3',
    title: 'Best Pizza in Town #43',
    content:
      "Tried the new pizza place downtown and it was incredible! Definitely the best pizza I've had in a long time.",
    category: 'news',
    timestamp: '2025-05-15T14:38:45.078452',
    likes: 148,
    reposts: 49,
    bookmarks: 17,
    comments: 1,
    views: 955,
    likedBy: ['3'],
  },
  {
    id: '44',
    userId: '3',
    username: 'gamerpro',
    displayName: 'GamerPro',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Gamer',
    verified: true,
    categoryId: '4',
    title: 'New Game Release #44',
    content:
      'Hyped for the new game releasing next week! Anyone else excited to play?',
    category: 'gaming',
    timestamp: '2025-05-15T14:33:45.078452',
    likes: 53,
    reposts: 29,
    bookmarks: 20,
    comments: 45,
    views: 838,
    likedBy: ['2', '5'],
  },
  {
    id: '45',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '5',
    title: 'Upcoming Marathon #45',
    content:
      'Training for the upcoming marathon. Any tips for long-distance running?',
    category: 'travel',
    timestamp: '2025-05-15T14:28:45.078452',
    likes: 254,
    reposts: 11,
    bookmarks: 9,
    comments: 18,
    views: 951,
    likedBy: ['3', '1', '2'],
  },
  {
    id: '46',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '1',
    title: 'The Future of AI #46',
    content:
      'What are your thoughts on the future of artificial intelligence? Share your predictions!',
    category: 'sports',
    timestamp: '2025-05-15T14:23:45.078452',
    likes: 129,
    reposts: 21,
    bookmarks: 25,
    comments: 44,
    views: 103,
    likedBy: ['3', '2', '4'],
  },
  {
    id: '47',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '2',
    title: 'Exploring Southeast Asia #47',
    content:
      'Just got back from an amazing trip to Southeast Asia. Highly recommend visiting Thailand and Vietnam!',
    category: 'sports',
    timestamp: '2025-05-15T14:18:45.078452',
    likes: 104,
    reposts: 44,
    bookmarks: 17,
    comments: 32,
    views: 824,
    likedBy: ['3'],
  },
  {
    id: '48',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '3',
    title: 'Best Pizza in Town #48',
    content:
      "Tried the new pizza place downtown and it was incredible! Definitely the best pizza I've had in a long time.",
    category: 'news',
    timestamp: '2025-05-15T14:13:45.078452',
    likes: 287,
    reposts: 22,
    bookmarks: 16,
    comments: 12,
    views: 243,
    likedBy: ['2', '2'],
  },
  {
    id: '49',
    userId: '3',
    username: 'gamerpro',
    displayName: 'GamerPro',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Gamer',
    verified: true,
    categoryId: '4',
    title: 'New Game Release #49',
    content:
      'Hyped for the new game releasing next week! Anyone else excited to play?',
    category: 'gaming',
    timestamp: '2025-05-15T14:08:45.078452',
    likes: 88,
    reposts: 60,
    bookmarks: 22,
    comments: 1,
    views: 779,
    likedBy: ['5'],
  },
  {
    id: '50',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '5',
    title: 'Upcoming Marathon #50',
    content:
      'Training for the upcoming marathon. Any tips for long-distance running?',
    category: 'travel',
    timestamp: '2025-05-15T14:03:45.078452',
    likes: 231,
    reposts: 49,
    bookmarks: 35,
    comments: 13,
    views: 210,
    likedBy: ['2', '2', '2'],
  },
  {
    id: '51',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '1',
    title: 'The Future of AI #51',
    content:
      'What are your thoughts on the future of artificial intelligence? Share your predictions!',
    category: 'sports',
    timestamp: '2025-05-15T13:58:45.078452',
    likes: 53,
    reposts: 36,
    bookmarks: 13,
    comments: 11,
    views: 380,
    likedBy: ['1', '3', '2'],
  },
  {
    id: '52',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '2',
    title: 'Exploring Southeast Asia #52',
    content:
      'Just got back from an amazing trip to Southeast Asia. Highly recommend visiting Thailand and Vietnam!',
    category: 'sports',
    timestamp: '2025-05-15T13:53:45.078452',
    likes: 294,
    reposts: 38,
    bookmarks: 16,
    comments: 47,
    views: 904,
    likedBy: ['1', '2'],
  },
  {
    id: '53',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '3',
    title: 'Best Pizza in Town #53',
    content:
      "Tried the new pizza place downtown and it was incredible! Definitely the best pizza I've had in a long time.",
    category: 'news',
    timestamp: '2025-05-15T13:48:45.078452',
    likes: 68,
    reposts: 44,
    bookmarks: 30,
    comments: 31,
    views: 522,
    likedBy: ['5', '5'],
  },
  {
    id: '54',
    userId: '3',
    username: 'gamerpro',
    displayName: 'GamerPro',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Gamer',
    verified: true,
    categoryId: '4',
    title: 'New Game Release #54',
    content:
      'Hyped for the new game releasing next week! Anyone else excited to play?',
    category: 'gaming',
    timestamp: '2025-05-15T13:43:45.078452',
    likes: 243,
    reposts: 35,
    bookmarks: 37,
    comments: 1,
    views: 860,
    likedBy: ['1', '3'],
  },
  {
    id: '55',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '5',
    title: 'Upcoming Marathon #55',
    content:
      'Training for the upcoming marathon. Any tips for long-distance running?',
    category: 'travel',
    timestamp: '2025-05-15T13:38:45.078452',
    likes: 222,
    reposts: 59,
    bookmarks: 12,
    comments: 14,
    views: 387,
    likedBy: ['5', '2'],
  },
  {
    id: '56',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '1',
    title: 'The Future of AI #56',
    content:
      'What are your thoughts on the future of artificial intelligence? Share your predictions!',
    category: 'sports',
    timestamp: '2025-05-15T13:33:45.078452',
    likes: 149,
    reposts: 54,
    bookmarks: 33,
    comments: 40,
    views: 725,
    likedBy: ['2', '5', '4'],
  },
  {
    id: '57',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '2',
    title: 'Exploring Southeast Asia #57',
    content:
      'Just got back from an amazing trip to Southeast Asia. Highly recommend visiting Thailand and Vietnam!',
    category: 'sports',
    timestamp: '2025-05-15T13:28:45.078452',
    likes: 60,
    reposts: 14,
    bookmarks: 19,
    comments: 18,
    views: 331,
    likedBy: ['4', '5', '1'],
  },
  {
    id: '58',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '3',
    title: 'Best Pizza in Town #58',
    content:
      "Tried the new pizza place downtown and it was incredible! Definitely the best pizza I've had in a long time.",
    category: 'news',
    timestamp: '2025-05-15T13:23:45.078452',
    likes: 129,
    reposts: 41,
    bookmarks: 37,
    comments: 13,
    views: 483,
    likedBy: ['4', '1'],
  },
  {
    id: '59',
    userId: '3',
    username: 'gamerpro',
    displayName: 'GamerPro',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Gamer',
    verified: true,
    categoryId: '4',
    title: 'New Game Release #59',
    content:
      'Hyped for the new game releasing next week! Anyone else excited to play?',
    category: 'gaming',
    timestamp: '2025-05-15T13:18:45.078452',
    likes: 100,
    reposts: 14,
    bookmarks: 13,
    comments: 46,
    views: 746,
    likedBy: ['2'],
  },
  {
    id: '60',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '5',
    title: 'Upcoming Marathon #60',
    content:
      'Training for the upcoming marathon. Any tips for long-distance running?',
    category: 'travel',
    timestamp: '2025-05-15T13:13:45.078452',
    likes: 125,
    reposts: 53,
    bookmarks: 20,
    comments: 22,
    views: 164,
    likedBy: ['4'],
  },
  {
    id: '61',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '1',
    title: 'The Future of AI #61',
    content:
      'What are your thoughts on the future of artificial intelligence? Share your predictions!',
    category: 'sports',
    timestamp: '2025-05-15T13:08:45.078452',
    likes: 107,
    reposts: 38,
    bookmarks: 37,
    comments: 46,
    views: 396,
    likedBy: ['3', '1', '2'],
  },
  {
    id: '62',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '2',
    title: 'Exploring Southeast Asia #62',
    content:
      'Just got back from an amazing trip to Southeast Asia. Highly recommend visiting Thailand and Vietnam!',
    category: 'sports',
    timestamp: '2025-05-15T13:03:45.078452',
    likes: 119,
    reposts: 15,
    bookmarks: 22,
    comments: 29,
    views: 707,
    likedBy: ['4'],
  },
  {
    id: '63',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '3',
    title: 'Best Pizza in Town #63',
    content:
      "Tried the new pizza place downtown and it was incredible! Definitely the best pizza I've had in a long time.",
    category: 'news',
    timestamp: '2025-05-15T12:58:45.078452',
    likes: 299,
    reposts: 54,
    bookmarks: 5,
    comments: 28,
    views: 254,
    likedBy: ['4', '4', '2'],
  },
  {
    id: '64',
    userId: '3',
    username: 'gamerpro',
    displayName: 'GamerPro',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Gamer',
    verified: true,
    categoryId: '4',
    title: 'New Game Release #64',
    content:
      'Hyped for the new game releasing next week! Anyone else excited to play?',
    category: 'gaming',
    timestamp: '2025-05-15T12:53:45.078452',
    likes: 195,
    reposts: 46,
    bookmarks: 11,
    comments: 30,
    views: 823,
    likedBy: ['3', '2', '1'],
  },
  {
    id: '65',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '5',
    title: 'Upcoming Marathon #65',
    content:
      'Training for the upcoming marathon. Any tips for long-distance running?',
    category: 'travel',
    timestamp: '2025-05-15T12:48:45.078452',
    likes: 82,
    reposts: 23,
    bookmarks: 19,
    comments: 32,
    views: 817,
    likedBy: ['5', '4', '3'],
  },
  {
    id: '66',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '1',
    title: 'The Future of AI #66',
    content:
      'What are your thoughts on the future of artificial intelligence? Share your predictions!',
    category: 'sports',
    timestamp: '2025-05-15T12:43:45.078452',
    likes: 86,
    reposts: 47,
    bookmarks: 26,
    comments: 41,
    views: 660,
    likedBy: ['2', '2', '2'],
  },
  {
    id: '67',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '2',
    title: 'Exploring Southeast Asia #67',
    content:
      'Just got back from an amazing trip to Southeast Asia. Highly recommend visiting Thailand and Vietnam!',
    category: 'sports',
    timestamp: '2025-05-15T12:38:45.078452',
    likes: 91,
    reposts: 56,
    bookmarks: 17,
    comments: 32,
    views: 994,
    likedBy: ['5'],
  },
  {
    id: '68',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '3',
    title: 'Best Pizza in Town #68',
    content:
      "Tried the new pizza place downtown and it was incredible! Definitely the best pizza I've had in a long time.",
    category: 'news',
    timestamp: '2025-05-15T12:33:45.078452',
    likes: 224,
    reposts: 24,
    bookmarks: 39,
    comments: 49,
    views: 540,
    likedBy: ['4'],
  },
  {
    id: '69',
    userId: '3',
    username: 'gamerpro',
    displayName: 'GamerPro',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Gamer',
    verified: true,
    categoryId: '4',
    title: 'New Game Release #69',
    content:
      'Hyped for the new game releasing next week! Anyone else excited to play?',
    category: 'gaming',
    timestamp: '2025-05-15T12:28:45.078452',
    likes: 99,
    reposts: 32,
    bookmarks: 10,
    comments: 17,
    views: 925,
    likedBy: ['2', '4', '2'],
  },
  {
    id: '70',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '5',
    title: 'Upcoming Marathon #70',
    content:
      'Training for the upcoming marathon. Any tips for long-distance running?',
    category: 'travel',
    timestamp: '2025-05-15T12:23:45.078452',
    likes: 251,
    reposts: 23,
    bookmarks: 6,
    comments: 5,
    views: 617,
    likedBy: ['2', '1', '4'],
  },
  {
    id: '71',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '1',
    title: 'The Future of AI #71',
    content:
      'What are your thoughts on the future of artificial intelligence? Share your predictions!',
    category: 'sports',
    timestamp: '2025-05-15T12:18:45.078452',
    likes: 93,
    reposts: 20,
    bookmarks: 15,
    comments: 15,
    views: 847,
    likedBy: ['4', '3'],
  },
  {
    id: '72',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '2',
    title: 'Exploring Southeast Asia #72',
    content:
      'Just got back from an amazing trip to Southeast Asia. Highly recommend visiting Thailand and Vietnam!',
    category: 'sports',
    timestamp: '2025-05-15T12:13:45.078452',
    likes: 83,
    reposts: 23,
    bookmarks: 37,
    comments: 47,
    views: 310,
    likedBy: ['2'],
  },
  {
    id: '73',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '3',
    title: 'Best Pizza in Town #73',
    content:
      "Tried the new pizza place downtown and it was incredible! Definitely the best pizza I've had in a long time.",
    category: 'news',
    timestamp: '2025-05-15T12:08:45.078452',
    likes: 64,
    reposts: 27,
    bookmarks: 9,
    comments: 1,
    views: 810,
    likedBy: ['2', '1'],
  },
  {
    id: '74',
    userId: '3',
    username: 'gamerpro',
    displayName: 'GamerPro',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Gamer',
    verified: true,
    categoryId: '4',
    title: 'New Game Release #74',
    content:
      'Hyped for the new game releasing next week! Anyone else excited to play?',
    category: 'gaming',
    timestamp: '2025-05-15T12:03:45.078452',
    likes: 181,
    reposts: 12,
    bookmarks: 19,
    comments: 31,
    views: 874,
    likedBy: ['2', '1', '1'],
  },
  {
    id: '75',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '5',
    title: 'Upcoming Marathon #75',
    content:
      'Training for the upcoming marathon. Any tips for long-distance running?',
    category: 'travel',
    timestamp: '2025-05-15T11:58:45.078452',
    likes: 204,
    reposts: 48,
    bookmarks: 14,
    comments: 20,
    views: 509,
    likedBy: ['5', '2'],
  },
  {
    id: '76',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '1',
    title: 'The Future of AI #76',
    content:
      'What are your thoughts on the future of artificial intelligence? Share your predictions!',
    category: 'sports',
    timestamp: '2025-05-15T11:53:45.078452',
    likes: 235,
    reposts: 47,
    bookmarks: 25,
    comments: 36,
    views: 690,
    likedBy: ['3'],
  },
  {
    id: '77',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '2',
    title: 'Exploring Southeast Asia #77',
    content:
      'Just got back from an amazing trip to Southeast Asia. Highly recommend visiting Thailand and Vietnam!',
    category: 'sports',
    timestamp: '2025-05-15T11:48:45.078452',
    likes: 104,
    reposts: 11,
    bookmarks: 6,
    comments: 15,
    views: 345,
    likedBy: ['3', '2'],
  },
  {
    id: '78',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '3',
    title: 'Best Pizza in Town #78',
    content:
      "Tried the new pizza place downtown and it was incredible! Definitely the best pizza I've had in a long time.",
    category: 'news',
    timestamp: '2025-05-15T11:43:45.078452',
    likes: 80,
    reposts: 50,
    bookmarks: 32,
    comments: 0,
    views: 506,
    likedBy: ['1', '3', '5'],
  },
  {
    id: '79',
    userId: '3',
    username: 'gamerpro',
    displayName: 'GamerPro',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Gamer',
    verified: true,
    categoryId: '4',
    title: 'New Game Release #79',
    content:
      'Hyped for the new game releasing next week! Anyone else excited to play?',
    category: 'gaming',
    timestamp: '2025-05-15T11:38:45.078452',
    likes: 160,
    reposts: 28,
    bookmarks: 11,
    comments: 48,
    views: 280,
    likedBy: ['2'],
  },
  {
    id: '80',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '5',
    title: 'Upcoming Marathon #80',
    content:
      'Training for the upcoming marathon. Any tips for long-distance running?',
    category: 'travel',
    timestamp: '2025-05-15T11:33:45.078452',
    likes: 80,
    reposts: 40,
    bookmarks: 19,
    comments: 11,
    views: 543,
    likedBy: ['4', '1'],
  },
  {
    id: '81',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '1',
    title: 'The Future of AI #81',
    content:
      'What are your thoughts on the future of artificial intelligence? Share your predictions!',
    category: 'sports',
    timestamp: '2025-05-15T11:28:45.078452',
    likes: 143,
    reposts: 59,
    bookmarks: 27,
    comments: 5,
    views: 925,
    likedBy: ['4'],
  },
  {
    id: '82',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '2',
    title: 'Exploring Southeast Asia #82',
    content:
      'Just got back from an amazing trip to Southeast Asia. Highly recommend visiting Thailand and Vietnam!',
    category: 'sports',
    timestamp: '2025-05-15T11:23:45.078452',
    likes: 197,
    reposts: 18,
    bookmarks: 11,
    comments: 19,
    views: 955,
    likedBy: ['3', '5', '3'],
  },
  {
    id: '83',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '3',
    title: 'Best Pizza in Town #83',
    content:
      "Tried the new pizza place downtown and it was incredible! Definitely the best pizza I've had in a long time.",
    category: 'news',
    timestamp: '2025-05-15T11:18:45.078452',
    likes: 85,
    reposts: 36,
    bookmarks: 14,
    comments: 26,
    views: 568,
    likedBy: ['3'],
  },
  {
    id: '84',
    userId: '3',
    username: 'gamerpro',
    displayName: 'GamerPro',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Gamer',
    verified: true,
    categoryId: '4',
    title: 'New Game Release #84',
    content:
      'Hyped for the new game releasing next week! Anyone else excited to play?',
    category: 'gaming',
    timestamp: '2025-05-15T11:13:45.078452',
    likes: 262,
    reposts: 60,
    bookmarks: 40,
    comments: 11,
    views: 316,
    likedBy: ['3', '1', '3'],
  },
  {
    id: '85',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '5',
    title: 'Upcoming Marathon #85',
    content:
      'Training for the upcoming marathon. Any tips for long-distance running?',
    category: 'travel',
    timestamp: '2025-05-15T11:08:45.078452',
    likes: 177,
    reposts: 32,
    bookmarks: 26,
    comments: 10,
    views: 365,
    likedBy: ['5'],
  },
  {
    id: '86',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '1',
    title: 'The Future of AI #86',
    content:
      'What are your thoughts on the future of artificial intelligence? Share your predictions!',
    category: 'sports',
    timestamp: '2025-05-15T11:03:45.078452',
    likes: 202,
    reposts: 42,
    bookmarks: 30,
    comments: 15,
    views: 606,
    likedBy: ['5', '1', '1'],
  },
  {
    id: '87',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '2',
    title: 'Exploring Southeast Asia #87',
    content:
      'Just got back from an amazing trip to Southeast Asia. Highly recommend visiting Thailand and Vietnam!',
    category: 'sports',
    timestamp: '2025-05-15T10:58:45.078452',
    likes: 96,
    reposts: 25,
    bookmarks: 19,
    comments: 48,
    views: 748,
    likedBy: ['5', '2', '4'],
  },
  {
    id: '88',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '3',
    title: 'Best Pizza in Town #88',
    content:
      "Tried the new pizza place downtown and it was incredible! Definitely the best pizza I've had in a long time.",
    category: 'news',
    timestamp: '2025-05-15T10:53:45.078452',
    likes: 178,
    reposts: 37,
    bookmarks: 17,
    comments: 13,
    views: 916,
    likedBy: ['5', '5'],
  },
  {
    id: '89',
    userId: '3',
    username: 'gamerpro',
    displayName: 'GamerPro',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Gamer',
    verified: true,
    categoryId: '4',
    title: 'New Game Release #89',
    content:
      'Hyped for the new game releasing next week! Anyone else excited to play?',
    category: 'gaming',
    timestamp: '2025-05-15T10:48:45.078452',
    likes: 190,
    reposts: 39,
    bookmarks: 31,
    comments: 16,
    views: 893,
    likedBy: ['2', '2'],
  },
  {
    id: '90',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '5',
    title: 'Upcoming Marathon #90',
    content:
      'Training for the upcoming marathon. Any tips for long-distance running?',
    category: 'travel',
    timestamp: '2025-05-15T10:43:45.078452',
    likes: 53,
    reposts: 38,
    bookmarks: 9,
    comments: 13,
    views: 560,
    likedBy: ['1', '1'],
  },
  {
    id: '91',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '1',
    title: 'The Future of AI #91',
    content:
      'What are your thoughts on the future of artificial intelligence? Share your predictions!',
    category: 'sports',
    timestamp: '2025-05-15T10:38:45.078452',
    likes: 258,
    reposts: 15,
    bookmarks: 27,
    comments: 5,
    views: 722,
    likedBy: ['5', '5', '4'],
  },
  {
    id: '92',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '2',
    title: 'Exploring Southeast Asia #92',
    content:
      'Just got back from an amazing trip to Southeast Asia. Highly recommend visiting Thailand and Vietnam!',
    category: 'sports',
    timestamp: '2025-05-15T10:33:45.078452',
    likes: 91,
    reposts: 49,
    bookmarks: 14,
    comments: 11,
    views: 981,
    likedBy: ['1'],
  },
  {
    id: '93',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '3',
    title: 'Best Pizza in Town #93',
    content:
      "Tried the new pizza place downtown and it was incredible! Definitely the best pizza I've had in a long time.",
    category: 'news',
    timestamp: '2025-05-15T10:28:45.078452',
    likes: 265,
    reposts: 48,
    bookmarks: 23,
    comments: 26,
    views: 876,
    likedBy: ['2', '4'],
  },
  {
    id: '94',
    userId: '3',
    username: 'gamerpro',
    displayName: 'GamerPro',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Gamer',
    verified: true,
    categoryId: '4',
    title: 'New Game Release #94',
    content:
      'Hyped for the new game releasing next week! Anyone else excited to play?',
    category: 'gaming',
    timestamp: '2025-05-15T10:23:45.078452',
    likes: 177,
    reposts: 56,
    bookmarks: 6,
    comments: 28,
    views: 908,
    likedBy: ['5'],
  },
  {
    id: '95',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '5',
    title: 'Upcoming Marathon #95',
    content:
      'Training for the upcoming marathon. Any tips for long-distance running?',
    category: 'travel',
    timestamp: '2025-05-15T10:18:45.078452',
    likes: 122,
    reposts: 30,
    bookmarks: 18,
    comments: 43,
    views: 701,
    likedBy: ['2', '5'],
  },
  {
    id: '96',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '1',
    title: 'The Future of AI #96',
    content:
      'What are your thoughts on the future of artificial intelligence? Share your predictions!',
    category: 'sports',
    timestamp: '2025-05-15T10:13:45.078452',
    likes: 209,
    reposts: 60,
    bookmarks: 23,
    comments: 18,
    views: 598,
    likedBy: ['5'],
  },
  {
    id: '97',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '2',
    title: 'Exploring Southeast Asia #97',
    content:
      'Just got back from an amazing trip to Southeast Asia. Highly recommend visiting Thailand and Vietnam!',
    category: 'sports',
    timestamp: '2025-05-15T10:08:45.078452',
    likes: 273,
    reposts: 22,
    bookmarks: 33,
    comments: 3,
    views: 344,
    likedBy: ['1', '1', '4'],
  },
  {
    id: '98',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    categoryId: '3',
    title: 'Best Pizza in Town #98',
    content:
      "Tried the new pizza place downtown and it was incredible! Definitely the best pizza I've had in a long time.",
    category: 'news',
    timestamp: '2025-05-15T10:03:45.078452',
    likes: 94,
    reposts: 14,
    bookmarks: 21,
    comments: 48,
    views: 444,
    likedBy: ['3', '1', '5'],
  },
  {
    id: '99',
    userId: '3',
    username: 'gamerpro',
    displayName: 'GamerPro',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Gamer',
    verified: true,
    categoryId: '4',
    title: 'New Game Release #99',
    content:
      'Hyped for the new game releasing next week! Anyone else excited to play?',
    category: 'gaming',
    timestamp: '2025-05-15T09:58:45.078452',
    likes: 248,
    reposts: 56,
    bookmarks: 10,
    comments: 15,
    views: 512,
    likedBy: ['2'],
  },
  {
    id: '100',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    categoryId: '5',
    title: 'Upcoming Marathon #100',
    content:
      'Training for the upcoming marathon. Any tips for long-distance running?',
    category: 'travel',
    timestamp: '2025-05-15T09:53:45.078452',
    likes: 296,
    reposts: 22,
    bookmarks: 21,
    comments: 41,
    views: 359,
    likedBy: ['3'],
  },
];

export const Comments: CommentProps[] = [
  {
    id: '1',
    postId: '1',
    userId: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    content: 'AI is definitely going to change the world as we know it!',
    timestamp: new Date(),
    likes: 50,
    verified: false,
  },
  {
    id: '2',
    postId: '1',
    userId: '3',
    username: 'theresatekenah',
    displayName: 'Theresa Tekenah',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Theresa',
    content: "I'm excited about the potential of AI in healthcare.",
    timestamp: new Date(),
    likes: 45,
    verified: true,
  },
  {
    id: '3',
    postId: '2',
    userId: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    content:
      'Thailand is on my bucket list! Any specific places you recommend?',
    timestamp: new Date(),
    likes: 60,
    verified: true,
  },
];

export const Users: UserTypes[] = [
  {
    id: '1',
    username: 'johndoe',
    displayName: 'John Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    verified: true,
    bio: 'Tech enthusiast and coffee lover',
    followers: ['4', '3', '5'],
    following: ['1', '2', '3'],
    joined: new Date('2022-03-15'),
    email: 'john@example.com',
  },
  {
    id: '2',
    username: 'janedoe',
    displayName: 'Jane Doe',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    verified: false,
    bio: 'Travel blogger and photographer',
    followers: ['4', '3', '5'],
    following: ['1', '2', '3'],
    joined: new Date('2022-05-20'),
    email: 'jane@example.com',
  },
  {
    id: '3',
    username: 'gamerpro',
    displayName: 'GamerPro',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Gamer',
    verified: true,
    bio: 'Professional gamer and streamer',
    followers: ['4', '3', '5'],
    following: ['1', '2', '3'],
    joined: new Date('2021-10-05'),
    email: 'gamer@example.com',
  },
];

export const notificationData: NotificationItemProps[] = [
  {
    id: '1',
    type: 'like',
    user: {
      username: 'janedoe',
      displayName: 'Jane Doe',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    },
    content: 'liked your post',
    postId: '2',
    timestamp: new Date().toISOString(),
    read: false,
  },
  {
    id: '2',
    type: 'follow',
    user: {
      username: 'theresatekenah',
      displayName: 'Theresa Tekenah',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Theresa',
    },
    content: 'followed you',
    timestamp: new Date(Date.now() - 86400000).toISOString(), // 1 day ago
    read: true,
  },
  {
    id: '3',
    type: 'reply',
    user: {
      username: 'janedoe',
      displayName: 'Jane Doe',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Jane',
    },
    content: 'replied to your post',
    postId: '1',
    timestamp: new Date(Date.now() - 172800000).toISOString(), // 2 days ago
    read: true,
  },
];
