import type {Metadata} from 'next';
import {
  Geist,
  Geist_Mono,
  Lato,
  Nunito,
  Oswald,
  Poppins,
  Roboto,
} from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const poppinsFont = Poppins({
  weight: '400',
  variable: '--font-poppins',
  subsets: ['latin'],
});

export const robotoFont = Roboto({
  //weight: '400',
  subsets: ['latin'],
});

export const nunitoFont = Nunito({
  //weight: '400',
  variable: '--font-nunito',
  subsets: ['latin'],
});

export const latoFont = Lato({
  weight: '400',
  subsets: ['latin'],
});

const oswaldFont = Oswald({
  weight: '400',
  variable: '--font-oswald',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunitoFont.className}  antialiased`}>{children}</body>
    </html>
  );
}
